services:
  - type: web
    name: appointment-system-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: static
    name: appointment-system
    buildCommand: npm run build
    publishDirectory: build
    envVars:
      - key: VITE_API_URL
        value: https://appointment-system-backend-n8dk.onrender.com
