services:
  - type: web
    name: lvappointease-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: static
    name: lvappointease
    buildCommand: npm run build
    publishDirectory: dist
    envVars:
      - key: VITE_API_URL
        value: https://appointease-backend.onrender.com
