// models/appointment/studentSchema.js
const mongoose = require("mongoose");

const studentSchema = new mongoose.Schema({
  surname: { type: String, required: true, trim: true },
  firstName: { type: String, required: true, trim: true },
  middleName: { type: String, trim: true },
  lastSchoolYearAttended: {
    type: String,
    required: true,
    match: /^\d{4}\s*[-–]\s*\d{4}$/,
  },
  courseOrStrand: {
    type: String,
    enum: [
      "Grade 1",
      "Grade 2",
      "Grade 3",
      "Grade 4",
      "Grade 5",
      "Grade 6",
      "Grade 7",
      "Grade 8",
      "Grade 9",
      "Grade 10",
      "Grade 11 - STEM",
      "Grade 11 - ABM",
      "Grade 12 - STEM",
      "Grade 12 - ABM",
      "BSAIS - 1st Year",
      "BSAIS - 2nd Year",
      "BSAIS - 3rd Year",
      "BSAIS - 4th Year",
      "BSA - 1st Year",
      "BSA - 2nd Year",
      "BSA - 3rd Year",
      "BSA - 4th Year",
      "BAB - 1st Year",
      "BAB - 2nd Year",
      "BAB - 3rd Year",
      "BAB - 4th Year",
      "BSSW - 1st Year",
      "BSSW - 2nd Year",
      "BSSW - 3rd Year",
      "BSSW - 4th Year",
      "ACT - 1st Year",
      "ACT - 2nd Year",
      "BSIS - 1st Year",
      "BSIS - 2nd Year",
      "BSIS - 3rd Year",
      "BSIS - 4th Year",
    ],
    required: true,
  },
  presentAddress: { type: String, required: true, trim: true },
  contactNumber: { type: String, required: true, match: /^09\d{9}$/ },
  emailAddress: {
    type: String,
    required: true,
    lowercase: true,
    match: /^\S+@\S+\.\S+$/,
  },
});

module.exports = mongoose.model("Student", studentSchema);
